hlxsites/servicenow

- .eslintrc.js
- scripts/dom-helpers.js
Test URLs:
- After: https://dom-helpers--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
> feat: Add Dom Helpers

- styles/styles.css
Parial for #1 
Test URLs:
- After: https://author--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
> 1 - Style Sidebar links and Author

- blocks/cards/cards.css
- blocks/cards/cards.js
- scripts/scripts.js
- styles/styles.css
Partial fix for #7. Needs a bit more finetuning on the CSS. Opening this PR to have it for demo purposes this evening.
Test URLs:
- After: https://cards--servicenow--hlxsites.hlx.live/blogs
> 7 - [Homepage] Cards

- helix-query.yaml
Partial for #19 . Setup initial indexing for US only 
Test URLs:
- After: https://indexing--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
> 19 - Setup Indexing

- blocks/blog-list/blog-list.js
- scripts/scripts.js
Test URLs:
- After: https://locale--servicenow--hlxsites.hlx.live/blogs/topics/ai-and-automation
> feat: Globally track locale aware information

- 404.html
- scripts/scripts.js
Fixes #25
Test URLs:
- After: https://issue25--servicenow--hlxsites.hlx.live/blogs
> 404 Handler

- styles/styles.css
Test URLs:
Blog Page:
- After: https://css-fixes--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
> fix: first section delimiter

- helix-query.yaml
Fix #31 
Test URLs:
- After: https://31-fulltextidx--servicenow--hlxsites.hlx.live/blogs
> 31 - Full Text Index

- blocks/blog-list/blog-list.js
- blocks/cards/cards.js
- scripts/scripts.js
Fix #70
Test URLs:
New Homepage:
- Before: https://main--servicenow--hlxsites.hlx.live/drafts/tuicu/blogs-automated
- After: https://homepage--servicenow--hlxsites.hlx.live/drafts/tuicu/blogs-automated
Topic Page:
- After: https://homepage--servicenow--hlxsites.hlx.live/blogs/topics/ai-and-automation
Category Page:
- After: https://homepage--servicenow--hlxsites.hlx.live/blogs/category/company-news
> 70 - [Homepage] Automate Homepage Behaviour

- helix-query.yaml
Test URLs:
- After: https://<branch>--servicenow--hlxsites.hlx.live/
> setup indexing for remaining geo's

- scripts/scripts.js
- styles/styles.css
Fix #51 
Test URLs:
- After: https://fixes-issue51--servicenow--hlxsites.hlx.live/blogs
> 51 - [Homepage] Style h3s with line

- README.md
- blocks/blog-list/blog-list.js
- blocks/cards/cards.js
- helix-query.yaml
- scripts/delayed.js
- scripts/scripts.js
Fix #72
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/fr/blogs/2023/pourquoi-il-faut-preparer-les-employes-a-l-avenir-du-travail
- After: https://72-geotopic--servicenow--hlxsites.hlx.live/fr/blogs/2023/pourquoi-il-faut-preparer-les-employes-a-l-avenir-du-travail
> 72 geotopic

- helix-query.yaml
Partial for #94
Test URLs:
- After: https://index-trends--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
> 94 - "New Trend" and "Trend" Metadata

- blocks/blog-list/blog-list.css
- blocks/blog-list/blog-list.js
Fix #81 
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/topics/customer-stories
- After: https://81-cust-stories--servicenow--hlxsites.hlx.live/blogs/topics/customer-stories
> Adding styling for the customer stories

- blocks/blog-list/blog-list.js
- scripts/scripts.js
Partial for #94
Test URLs:
New Change (use New Trend for filtering instead of Topic)
- After: https://filter-newtrend--servicenow--hlxsites.hlx.live/blogs/topics/ai-and-automation
Category: (as before, still working)
- After: https://filter-newtrend--servicenow--hlxsites.hlx.live/blogs/category/company-news
Year: (as before, still working)
- After: https://filter-newtrend--servicenow--hlxsites.hlx.live/blogs/2023 …
> 94 - "New Trend" and "Trend" filters

- blocks/social-share/social-share.css
Fix #88 
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/demo/veterans-legacies-tokens-service
- After: https://88-spacing--servicenow--hlxsites.hlx.live/blogs/2023/demo/veterans-legacies-tokens-service
> Adding top padding for social share buttons

- blocks/blogheader/blogheader.js
- blocks/cards/cards.js
- blocks/fragment/fragment.js
- scripts/scripts.js
The following PR:
* Autoblocks for Category/Year/Topic/Author pages the locale specific sidebar from `/fragments/sidebar-common-fragment`
* Autoblocks for Articles the locale specific sidebar from `/fragments/sidebar-article-fragment`
* Implements the rules for Featured and Trends & Research cards
* Still eager loads the fragment it sidebar as it is critical for the layout and we want to make sure we don't cause CLS
* Defers the loading of subblocks from the sidebar fragment to prioritise the FCP and LCP blocks first
Fix #99 
Test URLs:
Homepage (manual edited inlined sidebar, not auto-blocked)
- After: https://sidebar-rules--servicenow--hlxsites.hlx.live/blogs
Blog Article
- Before: …
> 99 - Sidebar rules

- blocks/blogheader/blogheader.css
- styles/styles.css
Test URLs:
- After: https://headercolor--servicenow--hlxsites.hlx.live/blogs
> fix - Use correct brand color for blog nav

- scripts/scripts.js
Fix #47 
Test URLs:
- After: [https://<branch>--servicenow--hlxsites.hlx.live/](https://issue47--servicenow--hlxsites.hlx.live/blogs)
> update page title

- blocks/blog-list/blog-list.css
- blocks/cards/cards.css
Fix #48 
Test URLs:
- After: [https://<branch>--servicenow--hlxsites.hlx.live/](https://issue48--servicenow--hlxsites.hlx.live/blogs/category/company-news)
in safari
> fixed safari, card width issue.

- tools/sidekick/config.json
Fix #18
Test URLs:
- After: https://18-library--servicenow--hlxsites.hlx.live/blogs
> Adding sidekick library to the config

- scripts/scripts.js
adding the logic to determine to open the link in new tab or current
Fix #64
Test URLs:
- After: https://64-linkhandling--servicenow--hlxsites.hlx.live/blogs/2023/maximize-efficiency-hyperautomation
> adding the logic to determine to open the link in new tab or current

- blocks/embed/embed.js
- blocks/social-share/social-share.js
- scripts/scripts.js
Fix #60
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/demo/3-ways-enhance-digital-experiences
- After: https://feat-analytics--servicenow--hlxsites.hlx.live/blogs/2023/demo/3-ways-enhance-digital-experiences
> Tracking of video and social share

- blocks/cards/cards.js
Fix #125
Test URLs:
- After: https://fix-topic--servicenow--hlxsites.hlx.live/blogs
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2022/from-reactive-proactive-field-service
- After: https://fix-topic--servicenow--hlxsites.hlx.live/blogs/2022/from-reactive-proactive-field-service
> fix - first card topic label missing

- blocks/cards/cards.js
Fix #121 
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/tools/sidekick/library.html?plugin=blocks
- After: https://121-library--servicenow--hlxsites.hlx.live/tools/sidekick/library.html?plugin=blocks
> Prefixing image location with hostname when it doesnt exist

- scripts/scripts.js
Fix #139
Test URLs:
- After: https://fix-139--servicenow--hlxsites.hlx.live/blogs/2023/maximize-efficiency-hyperautomation
> 139 - Browser tab title suffix

- styles/styles.css
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/experience-strategy-can-boost-financials
- After: https://image-size--servicenow--hlxsites.hlx.live/blogs/2023/experience-strategy-can-boost-financials
> fix - Image sizing

- blocks/columns/columns.css
- scripts/scripts.js
- styles/styles.css
Fix #17 
Before: https://main--servicenow--hlxsites.hlx.live/blogs/author/mary-hain
After: https://issue17--servicenow--hlxsites.hlx.live/blogs/author/mary-hain
Before: https://main--servicenow--hlxsites.hlx.live/blogs/author/abhijit-mitra
After: https://issue17--servicenow--hlxsites.hlx.live/blogs/author/abhijit-mitra
Updated style for existing P tags without making much of a structural change. Also, maintained the responsiveness with specifying width is %. Let me know if this approach is fine as per the standards.
> updated style for author block

- blocks/blog-years/blog-years.js
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/fragments/sidebar-article-fragment-dynamic
- After: https://issue49-refactor--servicenow--hlxsites.hlx.live/blogs/fragments/sidebar-article-fragment-dynamic
> Issue49 refactor

- blogs/sitemap-index.xml
- helix-sitemap.yaml
- robots.txt
> [WIP] Sitemap for all blog pages

- helix-sitemap.yaml
> Add origin to helix-sitemap config

- blocks/cards/cards.css
Fix #93 
Test URLs:
- After: https://issue93--servicenow--hlxsites.hlx.live/blogs
> updated aspect ratio for mobile

- styles/styles.css
Fix #165 
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/why-process-mining-is-game-changer
- After: https://fix-h3s--servicenow--hlxsites.hlx.live/blogs/2023/why-process-mining-is-game-changer
> 164 - Vertical distance between text when headings are wrapped around

- blocks/embed/embed.js
- styles/styles.css
Fix #172 
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/uk/blogs/2022/banking-at-the-speed-of-risk
- After: https://fix-172--servicenow--hlxsites.hlx.live/uk/blogs/2022/banking-at-the-speed-of-risk
> 172 - Style blockqoute

- blocks/blog-topics/blog-topics.css
- blocks/blog-years/blog-years.css
- blocks/cards/cards.css
Test URLs:
- After: https://fix-margins--servicenow--hlxsites.hlx.live/blogs
> fix - margins

- blocks/blog-topics/blog-topics.js
Test URLs:
- After: https://excludesidebar--servicenow--hlxsites.hlx.live/blogs
> feat - allow excluding topic pages from sidebar

- blocks/embed/embed.js
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2019/shifting-customer-service-into-high-gear
- After: https://tunein--servicenow--hlxsites.hlx.live/blogs/2019/shifting-customer-service-into-high-gear
> feat - embed tune in

- blocks/table/table.css
- blocks/table/table.js
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2019/servicenow-using-own-products
- After: https://feat-table--servicenow--hlxsites.hlx.live/blogs/2019/servicenow-using-own-products
> Added table block

- aemeds/blocks/footer/footer.css
- aemeds/blocks/header/header.css
Fix: Remove list markers in header
Request from NaaS Team: remove padding top.
Test URLs:
- After: https://naas-fixes--servicenow--hlxsites.hlx.live/blogs
> fix - NaaS Styling

- aemeds/blocks/blogheader/blogheader.js
Optimise search results by:
* Evaluating results in chunks of 250
* Display the results before moving to the next chunk, don't wait until we looked at all results
* Display by chunk first the results that have the search terms in the header, than meta and only after content
Fix #75
Test URLs:
- After: https://optimise-search--servicenow--hlxsites.hlx.live/blogs
> 75 - optimise blog search performance

- aemeds/blocks/cards/cards.css
Test URLs:
- After: https://media-query--servicenow--hlxsites.hlx.live/blogs
> fix - horizontal scroll on 768 screen size

- aemeds/blocks/blogheader/blogheader.css
Fix #176 
Test URLs:
US:
- After: https://fix-176--servicenow--hlxsites.hlx.live/blogs
UK:
- Before: https://main--servicenow--hlxsites.hlx.live/uk/blogs
- After: https://fix-176--servicenow--hlxsites.hlx.live/uk/blogs
FR:
- Before: https://main--servicenow--hlxsites.hlx.live/fr/blogs
- After: https://fix-176--servicenow--hlxsites.hlx.live/fr/blogs
DE:
- Before: https://main--servicenow--hlxsites.hlx.live/de/blogs
- After: https://fix-176--servicenow--hlxsites.hlx.live/de/blogs
NL:
- Before: https://main--servicenow--hlxsites.hlx.live/nl/blogs
- After: …
> 176 - Blog Header Geosites fixes

- aemeds/blocks/blogheader/blogheader.js
Test URLs:
- After: https://blogheaderfix--servicenow--hlxsites.hlx.live/blogs
> fix - Blog Header expanded when resizing from desktop to mobile

- aemeds/blocks/cards/cards.js
Test URLs:
- After: https://cards-placeholder--servicenow--hlxsites.hlx.live/blogs/2023
> fix - Add placeholder image, in case the post doesn't have one

- aemeds/styles/styles.css
Fix #92 
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/drafts/tuicu/buttons
- After: https://buttons--servicenow--hlxsites.hlx.live/drafts/tuicu/buttons
> 92 - styles for primary and secondary buttons

- aemeds/blocks/blogheader/blogheader.css
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/drafts/tuicu/buttons
- After: https://fix-menu-button--servicenow--hlxsites.hlx.live/drafts/tuicu/buttons
> fix - Blog Header Button

- aemeds/blocks/cards/cards.css
- aemeds/blocks/cards/cards.js
Test URLs:
- After: https://cards-mobile--servicenow--hlxsites.hlx.live/blogs
> fix - Additional Mobile Optimisations for Cards

- aemeds/blocks/blog-list/blog-list.css
- aemeds/blocks/blog-list/blog-list.js
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/category/product-news
- After: https://bloglist-more--servicenow--hlxsites.hlx.live/blogs/category/product-news
> feat: Load More button for Blog List

- aemeds/blocks/blogheader/blogheader.css
- aemeds/blocks/blogheader/blogheader.js
- aemeds/styles/styles.css
Test URLs:
- After: https://vqablogheader--servicenow--hlxsites.hlx.live/blogs
> fix: VQA Blog Header feedback

- aemeds/blocks/blog-list/blog-list.css
Test URLs:
- After: https://bloglistcta--servicenow--hlxsites.hlx.live/blogs/2023
> fix: VQA Blog List CTA

- aemeds/blocks/columns/columns.css
Fix Design Issue 9
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/author/abhi-rele
- After: https://ui-task-9--servicenow--hlxsites.hlx.live/blogs/author/abhi-rele
> Image and text should be horizontally aligned

- aemeds/blocks/blogheader/blogheader.css
Test URLs:
- After: https://headerspacing--servicenow--hlxsites.hlx.live/blogs
> fix: VQA Feedback - Blog Header Distance

- aemeds/scripts/scripts.js
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/extended-reality-future-digital-learning
- After: https://links--servicenow--hlxsites.hlx.live/blogs/2023/extended-reality-future-digital-learning
> Open all servicenow.com subdomains in new tab except www.servicenow.com

- aemeds/blocks/blogheader/blogheader.js
Test URLs:
- After: https://search--servicenow--hlxsites.hlx.live/
> Ignored empty search tokens

- aemeds/blocks/social-share/social-share.js
Fix #206
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2024/fortune-worlds-most-admired-companies
- After: https://livedate--servicenow--hlxsites.hlx.live/blogs/2024/fortune-worlds-most-admired-companies
> Set live date required for social share

- aemeds/scripts/aem.js
- aemeds/scripts/delayed.js
- head.html
Test URLs:
With Launch Disabled
- Before: https://main--servicenow--hlxsites.hlx.live/blogs?disableLaunch=true
- After: https://headlaunch--servicenow--hlxsites.hlx.live/blogs?disableLaunch=true
With Launch
- After: https://headlaunch--servicenow--hlxsites.hlx.live/blogs
> fix: Load Adobe Launch in the head of the html

- aemeds/scripts/scripts.js
Test URLs:
- After: https://removeclickmessage--servicenow--hlxsites.hlx.live/blogs
> chore: remove click track console message

- aemeds/blocks/social-share/social-share.js
Fix https://github.com/hlxsites/servicenow/issues/206
Test URLs:
Before: https://main--servicenow--hlxsites.hlx.live/blogs/2024/fortune-worlds-most-admired-companies
After: https://live1604--servicenow--hlxsites.hlx.live/blogs/2024/fortune-worlds-most-admired-companies
> Live date 16/04/2024

- 404.html
CSS breakpoints were not working on the 404 page.
Fix #25
> 25 - 404 Handler: Improvement

- 404.html
Navigation in the iframe doesn't update the address bar. Will leave the initial implementation.
Fix #25
> fix: Revert 404 page as iframe

- aemeds/blocks/embed/embed.js
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2024/creative-efforts-preserve-planet?disableLaunch=true
- After: https://safaribrightcove--servicenow--hlxsites.hlx.live/blogs/2024/creative-efforts-preserve-planet?disableLaunch=true
> fix: Brightcove on Safari Mobile
