hlxsites/servicenow

helix-query.yaml
Improvements:
* Make the author link relative
* Exclude any fragments we might add in the `blog` folder from indexing 
Fix #19 
Test URLs:
- After: https://indexing2--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
=> 19 - Setup Indexing for US Blogs

scripts/scripts.js, styles/styles.css
Finalise Sidebar Section:
* Match paddings and screensizes form the original website
* Generalise the `Start Sidebar At Section` configuration
Fix #4 
Test URLs:
Home page:
- After: https://sidebar--servicenow--hlxsites.hlx.live/blogs
Blog page:
- After: https://sidebar--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
Filter page:
- After: …
=> 4 - Sidebar Section

blocks/blog-list/blog-list.js
Forgot to specify the `blogs` sheet in the call to the index. It still works because only the blogs fit the filter criteria, but it can be more efficient like this.
Fix #12
Test URLs:
Topic
- After: https://fix-list--servicenow--hlxsites.hlx.live/blogs/topics/ai-and-automation
Category
- After: https://fix-list--servicenow--hlxsites.hlx.live/blogs/category/company-news
Year
- After: …
=> 12 - [Block] Blog List

styles/styles.css
This PR fixes the section line when for when there is no sidebar (the implementation with sidebar was working before as well, the examples below are just to show that I'm not breaking that)
Part of #2 
Test URLs:
Without sidebar:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/author/mary-hain
- After: https://fix-line--servicenow--hlxsites.hlx.live/blogs/author/mary-hain
Above sidebar:
- After: https://fix-line--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
Side by side with sidebar:
- Before: …
=> trivial - Fix section line w/o sidebar

.gitignore, blocks/fragment/fragment.css, blocks/fragment/fragment.js, scripts/scripts.js
Sidebar with eager fragment loading
Partial for #16
US blog
Before: https://main--servicenow--hlxsites.hlx.live/
After: https://feature-16-sidebar-eager--servicenow--hlxsites.hlx.live/blogs/drafts/sardan/maximize-efficiency-hyperautomation
UK blog
Before: https://main--servicenow--hlxsites.hlx.live/
After: https://feature-16-sidebar-eager--servicenow--hlxsites.hlx.live/uk/blogs/drafts/sardan/maximize-efficiency-hyperautomation
UK blog
Before: https://main--servicenow--hlxsites.hlx.live/
After: https://feature-16-sidebar-eager--servicenow--hlxsites.hlx.live/blogs/2023/demo/maximize-efficiency-hyperautomation
=> Feature-16-sidebar-eager

blocks/blog-list/blog-list.js, blocks/cards/cards.js
After importing all ~200 blogs from 2023 and publishing them, the lighthouse score for the page with the 2023 card list dropped because of the TBT spiking.
This PR makes it so that only the first 20 cards are initially rendered and the rest are lazy rendered as the user scrolls to the end of the list.
Test URLs:
- After: https://optimise-list--servicenow--hlxsites.hlx.live/blogs/2023
=> Optimise Blog List with Lazy Rendering

styles/styles.css
Fix #137
Ordered list with numbers (fixed)
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2022/integrating-elevate-customer-loyalty
- After: https://fix-137--servicenow--hlxsites.hlx.live/blogs/2022/integrating-elevate-customer-loyalty
Unordered list with bullets (unchanged)
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2022/welcome-to-knowledge
- After: https://fix-137--servicenow--hlxsites.hlx.live/blogs/2022/welcome-to-knowledge
=> 137 - Ordered list styling removes the ordering

blocks/cards/cards.js, scripts/scripts.js
The default logic for awaiting the LCP image doesn't work well for blogs home page, as it is waiting for the first image present in the dom to load, which in that case, is in the sidebar. For the best LCP load time, we need to skip that waiting, quickly load the first card teaser and then wait for that image to load.
Before: LCP 1.7 - 2.2. LHS Score 99 - 100.
After: LCP 1.4 - 1.7. LHS Score 100.
Test URLs:
- After: https://homepage-lhs--servicenow--hlxsites.hlx.live/blogs
=> fix - Optimise LCP score in the homepage

styles/styles.css
Authoring team reported that the link underline is too far from the text. Switching it back to the way it was prior to #104 
Test URLs:
- After: https://fix-links--servicenow--hlxsites.hlx.live/blogs/2023/maximize-efficiency-hyperautomation
=> fix - Blog links underline should be closer to the text

helix-query.yaml
Test URLs:
- After: https://exclude-drafts--servicenow--hlxsites.hlx.live/blogs/2023/maximize-efficiency-hyperautomation
=> fix - exclude drafts folders from indexing

scripts/scripts.js
Fix locale selection in the JS:
* use the metadata if available. we normally set it in the bulk metadata.xls on all paths
* fix url prefix so blog header and copyright are correctly retrieved.
Test URLs:
US (blog header has ServiceNow Research)
- After: https://fix-locale--servicenow--hlxsites.hlx.live/blogs/2023/maximize-efficiency-hyperautomation
UK (blog header has EMEA Insights)
- Before: https://main--servicenow--hlxsites.hlx.live/uk/blogs/2023/uk-i-must-prepare-future-workplace
- After: https://fix-locale--servicenow--hlxsites.hlx.live/uk/blogs/2023/uk-i-must-prepare-future-workplace
=> fix - Locale selection and prefix

blocks/blog-list/blog-list.js, blocks/blog-topics/blog-topics.js, blocks/blog-years/blog-years.js, blocks/cards/cards.js, scripts/ffetch.js, scripts/scripts.js
The lighthouse score for the homepage and blog list pages had been declining since we've been importing more blog pages, as the size of the payload being transferred over the network had increased. This PR optimises the access to the index by transferring one chunk at a time, only when needed, instead of bringing all the entries in 1 go.
Additionally:
Fix #155
Test URLs:
- After: https://optimise-index--servicenow--hlxsites.hlx.live/blogs
- After: https://optimise-index--servicenow--hlxsites.hlx.live/blogs/2023
=> 155 - No category "ServiceNow Research" in homepage and sidebar + Optimise index

scripts/delayed.js, scripts/scripts.js
feat: Allow setting the launch version via query parameters.
fix: Set staging launch for hlx URLs (as requested by the customer)
Test URLs:
- After: https://launch--servicenow--hlxsites.hlx.live/blogs
=> feat - allow switching launch version

aemeds/blocks/blog-list/blog-list.css, aemeds/blocks/cards/cards.css
On small mobile screens, the read more CTA was getting overlapped with the rest of the text.
This was also happening on the original website:
This PR addresses this problem for small screens.
Test URLs:
- After: https://list-mobile--servicenow--hlxsites.hlx.live/blogs/2023
=> fix - Mobile Optimisation for BlogList

aemeds/blocks/social-share/social-share.js
Partial for #206
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2024/fortune-worlds-most-admired-companies
- After: https://socialshare-date--servicenow--hlxsites.hlx.live/blogs/2024/fortune-worlds-most-admired-companies
=> 206 - Adjust GoLive date into the social share component

aemeds/blocks/blogheader/blogheader.js
There was a small penalty in accessibility on desktop, because the search input didn't have an accessible description.
Test URLs:
- After: https://search-accessibility--servicenow--hlxsites.hlx.live/blogs
=> fix - Header Search Accessibility

aemeds/blocks/cards/cards.js
The customer mentioned that it is not the best experience for readers to have the currently opened blog in the sidebar.
Test URLs:
Homepage:
- After: https://exclude-current--servicenow--hlxsites.hlx.live/blogs
Blog Page:
- After: https://exclude-current--servicenow--hlxsites.hlx.live/blogs/2024/fast-time-value-washington-dc-release
=> feat: Exclude Current Blog from Sidebar

aemeds/blocks/cards/cards.css
Images on mobile in the sidebar cards should be aligned with the section title
Cards separator is too short when there is little text in the card
Test URLs:
- After: https://vqa-homepage--servicenow--hlxsites.hlx.live/blogs
=> fix: VQA Feedback for Cards

aemeds/blocks/blogheader/blogheader.css, aemeds/blocks/blogheader/blogheader.js
Fixes: Search icon is slow to move when selecting and deselecting the search bar.
Test URLs:
- After: https://searchicon--servicenow--hlxsites.hlx.live/blogs
=> fix: VQA - Search Box Animation

aemeds/blocks/embed/embed.css
Customer feedback:
> The video player on this blog is pulling the old brand colors for the play button and the bar across the bottom once the video is playing. Can all videos be updated to reflect the new brand colors? 
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/what-makes-servicenow-employees-stay
- After: https://bcvplayercolors--servicenow--hlxsites.hlx.live/blogs/2023/what-makes-servicenow-employees-stay
=> fix: Use new brand colors for the brightcove player

aemeds/blocks/blog-list/blog-list.js, aemeds/blocks/blog-topics/blog-topics.js, aemeds/blocks/blogheader/blogheader.js, aemeds/blocks/cards/cards.js, aemeds/scripts/scripts.js
Test URLs:
With Launch enabled
- After: https://evar30--servicenow--hlxsites.hlx.live/blogs
With Launch Disabled
- Before: https://main--servicenow--hlxsites.hlx.live/blogs?disableLaunch=true
- After: https://evar30--servicenow--hlxsites.hlx.live/blogs?disableLaunch=true
=> fix: Correctly Set eVar30

aemeds/blocks/blog-list/blog-list.js
Fix: The Card title was not being included in the evar22 information being sent when clicking a blog list card.
Test URLs:
With Launch
- After: https://listclickfix--servicenow--hlxsites.hlx.live/blogs/category/company-news
Without Launch
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/category/company-news?disableLaunch=true
- After: https://listclickfix--servicenow--hlxsites.hlx.live/blogs/category/company-news?disableLaunch=true
=> fix: Include card title in the Blog List eVar22

head.html
Allow disabling launch in production for 1 page to check performance through the servicenow CDN.
Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/ai-business-process-analyst-role
- After: https://disablelaunchprod--servicenow--hlxsites.hlx.live/blogs/2023/ai-business-process-analyst-role?disableLaunch=true
=> test: allow disabling launch in production for 1 page

head.html
Test URLs:
With Launch
- After: https://targetflickering--servicenow--hlxsites.hlx.live/blogs
With Launch Disabled
- Before: https://main--servicenow--hlxsites.hlx.live/blogs?disableLaunch=true
- After: https://targetflickering--servicenow--hlxsites.hlx.live/blogs?disableLaunch=true
=> fix: Configure Target to not hide the body when loaded

aemeds/blocks/social-share/social-share.js, aemeds/scripts/scripts.js
Click Track events are only sent if the `ctaText` and `destination` are also present.
Fix: #123
Test URLs:
With Launch
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2024/unique-career-growth-plan
- After: https://socialclicktrack--servicenow--hlxsites.hlx.live/blogs/2024/unique-career-growth-plan
With Launch Disabled
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2024/unique-career-growth-plan?disableLaunch=true
- After: https://socialclicktrack--servicenow--hlxsites.hlx.live/blogs/2024/unique-career-growth-plan?disableLaunch=true
=> fix: Soclial Share Click Track

404.html
Fix #25
The Content Security Policy from servicenow.com doesn't allow adding iframes for the `.live` and `.page` domains, but that doesn't prevent us from creating the iframe in production.
This PR when merged will introduce a canary logic so we can test in production if iframeing the 404 page would work, thus allowing us not to change the window location.
=> 25 - 404 Handler: Improvement
